// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: gateway.peer.proto

package peerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//ListLongConnectionReq 获取长连接列表请求
type ListLongConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *RequestHeader                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Filter  *ListLongConnectionReq_Filter `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	AllPods bool                          `protobuf:"varint,3,opt,name=allPods,proto3" json:"allPods,omitempty"` // 是否获取所有pod的长连接
}

func (x *ListLongConnectionReq) Reset() {
	*x = ListLongConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLongConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLongConnectionReq) ProtoMessage() {}

func (x *ListLongConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLongConnectionReq.ProtoReflect.Descriptor instead.
func (*ListLongConnectionReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ListLongConnectionReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListLongConnectionReq) GetFilter() *ListLongConnectionReq_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListLongConnectionReq) GetAllPods() bool {
	if x != nil {
		return x.AllPods
	}
	return false
}

//ListLongConnectionResp 获取长连接列表响应
type ListLongConnectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header          *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	LongConnections []*LongConnection `protobuf:"bytes,2,rep,name=longConnections,proto3" json:"longConnections,omitempty"`
}

func (x *ListLongConnectionResp) Reset() {
	*x = ListLongConnectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLongConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLongConnectionResp) ProtoMessage() {}

func (x *ListLongConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLongConnectionResp.ProtoReflect.Descriptor instead.
func (*ListLongConnectionResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ListLongConnectionResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListLongConnectionResp) GetLongConnections() []*LongConnection {
	if x != nil {
		return x.LongConnections
	}
	return nil
}

type GatewayKickLongConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *RequestHeader                       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Filter  *GatewayKickLongConnectionReq_Filter `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	AllPods bool                                 `protobuf:"varint,3,opt,name=allPods,proto3" json:"allPods,omitempty"` // 是否踢掉所有pod的长连接
}

func (x *GatewayKickLongConnectionReq) Reset() {
	*x = GatewayKickLongConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKickLongConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickLongConnectionReq) ProtoMessage() {}

func (x *GatewayKickLongConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickLongConnectionReq.ProtoReflect.Descriptor instead.
func (*GatewayKickLongConnectionReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayKickLongConnectionReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GatewayKickLongConnectionReq) GetFilter() *GatewayKickLongConnectionReq_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GatewayKickLongConnectionReq) GetAllPods() bool {
	if x != nil {
		return x.AllPods
	}
	return false
}

type GatewayKickLongConnectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header                 *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SuccessLongConnections []*LongConnection `protobuf:"bytes,2,rep,name=successLongConnections,proto3" json:"successLongConnections,omitempty"`
}

func (x *GatewayKickLongConnectionResp) Reset() {
	*x = GatewayKickLongConnectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKickLongConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickLongConnectionResp) ProtoMessage() {}

func (x *GatewayKickLongConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickLongConnectionResp.ProtoReflect.Descriptor instead.
func (*GatewayKickLongConnectionResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayKickLongConnectionResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GatewayKickLongConnectionResp) GetSuccessLongConnections() []*LongConnection {
	if x != nil {
		return x.SuccessLongConnections
	}
	return nil
}

//GatewayKeepAliveReq 保持连接请求
type GatewayKeepAliveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *GatewayKeepAliveReq) Reset() {
	*x = GatewayKeepAliveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKeepAliveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKeepAliveReq) ProtoMessage() {}

func (x *GatewayKeepAliveReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKeepAliveReq.ProtoReflect.Descriptor instead.
func (*GatewayKeepAliveReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayKeepAliveReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//GatewayKeepAliveResp 保持连接响应
type GatewayKeepAliveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *GatewayKeepAliveResp) Reset() {
	*x = GatewayKeepAliveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKeepAliveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKeepAliveResp) ProtoMessage() {}

func (x *GatewayKeepAliveResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKeepAliveResp.ProtoReflect.Descriptor instead.
func (*GatewayKeepAliveResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayKeepAliveResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//VerifyConnectionReq 验证连接 客户端拿着自己的公钥，请求网关，网关返回自己的公钥
type VerifyConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey []byte         `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *VerifyConnectionReq) Reset() {
	*x = VerifyConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectionReq) ProtoMessage() {}

func (x *VerifyConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectionReq.ProtoReflect.Descriptor instead.
func (*VerifyConnectionReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyConnectionReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VerifyConnectionReq) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type VerifyConnectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey []byte          `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *VerifyConnectionResp) Reset() {
	*x = VerifyConnectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectionResp) ProtoMessage() {}

func (x *VerifyConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectionResp.ProtoReflect.Descriptor instead.
func (*VerifyConnectionResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyConnectionResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *VerifyConnectionResp) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

//AuthConnectionReq 验证连接用户id和token
type AuthConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId string         `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Token  string         `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthConnectionReq) Reset() {
	*x = AuthConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnectionReq) ProtoMessage() {}

func (x *AuthConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnectionReq.ProtoReflect.Descriptor instead.
func (*AuthConnectionReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{8}
}

func (x *AuthConnectionReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AuthConnectionReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthConnectionReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthConnectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AuthConnectionResp) Reset() {
	*x = AuthConnectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnectionResp) ProtoMessage() {}

func (x *AuthConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnectionResp.ProtoReflect.Descriptor instead.
func (*AuthConnectionResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{9}
}

func (x *AuthConnectionResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AuthConnectionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthConnectionResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GatewayWriteDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *RequestHeader              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Filter  *GatewayWriteDataReq_Filter `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Content *GatewayWriteDataContent    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AllPods bool                        `protobuf:"varint,4,opt,name=allPods,proto3" json:"allPods,omitempty"` // 是否推送到所有pod
}

func (x *GatewayWriteDataReq) Reset() {
	*x = GatewayWriteDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayWriteDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayWriteDataReq) ProtoMessage() {}

func (x *GatewayWriteDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayWriteDataReq.ProtoReflect.Descriptor instead.
func (*GatewayWriteDataReq) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayWriteDataReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GatewayWriteDataReq) GetFilter() *GatewayWriteDataReq_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GatewayWriteDataReq) GetContent() *GatewayWriteDataContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GatewayWriteDataReq) GetAllPods() bool {
	if x != nil {
		return x.AllPods
	}
	return false
}

type GatewayWriteDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header                 *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SuccessLongConnections []*LongConnection `protobuf:"bytes,2,rep,name=successLongConnections,proto3" json:"successLongConnections,omitempty"`
}

func (x *GatewayWriteDataResp) Reset() {
	*x = GatewayWriteDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayWriteDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayWriteDataResp) ProtoMessage() {}

func (x *GatewayWriteDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayWriteDataResp.ProtoReflect.Descriptor instead.
func (*GatewayWriteDataResp) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{11}
}

func (x *GatewayWriteDataResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GatewayWriteDataResp) GetSuccessLongConnections() []*LongConnection {
	if x != nil {
		return x.SuccessLongConnections
	}
	return nil
}

type ListLongConnectionReq_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"` // length > 0 时有效
}

func (x *ListLongConnectionReq_Filter) Reset() {
	*x = ListLongConnectionReq_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLongConnectionReq_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLongConnectionReq_Filter) ProtoMessage() {}

func (x *ListLongConnectionReq_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLongConnectionReq_Filter.ProtoReflect.Descriptor instead.
func (*ListLongConnectionReq_Filter) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListLongConnectionReq_Filter) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GatewayKickLongConnectionReq_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"` // length > 0 时有效
}

func (x *GatewayKickLongConnectionReq_Filter) Reset() {
	*x = GatewayKickLongConnectionReq_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKickLongConnectionReq_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickLongConnectionReq_Filter) ProtoMessage() {}

func (x *GatewayKickLongConnectionReq_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickLongConnectionReq_Filter.ProtoReflect.Descriptor instead.
func (*GatewayKickLongConnectionReq_Filter) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GatewayKickLongConnectionReq_Filter) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GatewayWriteDataReq_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"` // length > 0 时有效
}

func (x *GatewayWriteDataReq_Filter) Reset() {
	*x = GatewayWriteDataReq_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_peer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayWriteDataReq_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayWriteDataReq_Filter) ProtoMessage() {}

func (x *GatewayWriteDataReq_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_peer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayWriteDataReq_Filter.ProtoReflect.Descriptor instead.
func (*GatewayWriteDataReq_Filter) Descriptor() ([]byte, []int) {
	return file_gateway_peer_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GatewayWriteDataReq_Filter) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_gateway_peer_proto protoreflect.FileDescriptor

var file_gateway_peer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x3d, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x1a, 0x22, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3c,
	0x0a, 0x0f, 0x6c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x6c, 0x6f, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd8, 0x01, 0x0a,
	0x1c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c, 0x6f, 0x6e, 0x67,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x1a, 0x22, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x1d, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x16, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x16, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x40, 0x0a, 0x13, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x65, 0x70,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x14, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65,
	0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x29,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x60, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x6c, 0x0a, 0x11, 0x41, 0x75, 0x74,
	0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x29,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x70, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xfd, 0x01, 0x0a, 0x13, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x73, 0x1a, 0x22, 0x0a, 0x06, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x14, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x4a,
	0x0a, 0x16, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x16, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xc6, 0x01, 0x0a, 0x11, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x62, 0x0a, 0x19, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c, 0x6f,
	0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c, 0x6f, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x4c,
	0x6f, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x32, 0xe7, 0x01, 0x0a, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x5a, 0x0a,
	0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x47, 0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70,
	0x65, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_peer_proto_rawDescOnce sync.Once
	file_gateway_peer_proto_rawDescData = file_gateway_peer_proto_rawDesc
)

func file_gateway_peer_proto_rawDescGZIP() []byte {
	file_gateway_peer_proto_rawDescOnce.Do(func() {
		file_gateway_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_peer_proto_rawDescData)
	})
	return file_gateway_peer_proto_rawDescData
}

var file_gateway_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gateway_peer_proto_goTypes = []interface{}{
	(*ListLongConnectionReq)(nil),               // 0: pb.ListLongConnectionReq
	(*ListLongConnectionResp)(nil),              // 1: pb.ListLongConnectionResp
	(*GatewayKickLongConnectionReq)(nil),        // 2: pb.GatewayKickLongConnectionReq
	(*GatewayKickLongConnectionResp)(nil),       // 3: pb.GatewayKickLongConnectionResp
	(*GatewayKeepAliveReq)(nil),                 // 4: pb.GatewayKeepAliveReq
	(*GatewayKeepAliveResp)(nil),                // 5: pb.GatewayKeepAliveResp
	(*VerifyConnectionReq)(nil),                 // 6: pb.VerifyConnectionReq
	(*VerifyConnectionResp)(nil),                // 7: pb.VerifyConnectionResp
	(*AuthConnectionReq)(nil),                   // 8: pb.AuthConnectionReq
	(*AuthConnectionResp)(nil),                  // 9: pb.AuthConnectionResp
	(*GatewayWriteDataReq)(nil),                 // 10: pb.GatewayWriteDataReq
	(*GatewayWriteDataResp)(nil),                // 11: pb.GatewayWriteDataResp
	(*ListLongConnectionReq_Filter)(nil),        // 12: pb.ListLongConnectionReq.Filter
	(*GatewayKickLongConnectionReq_Filter)(nil), // 13: pb.GatewayKickLongConnectionReq.Filter
	(*GatewayWriteDataReq_Filter)(nil),          // 14: pb.GatewayWriteDataReq.Filter
	(*RequestHeader)(nil),                       // 15: pb.RequestHeader
	(*ResponseHeader)(nil),                      // 16: pb.ResponseHeader
	(*LongConnection)(nil),                      // 17: pb.LongConnection
	(*GatewayWriteDataContent)(nil),             // 18: pb.GatewayWriteDataContent
}
var file_gateway_peer_proto_depIdxs = []int32{
	15, // 0: pb.ListLongConnectionReq.header:type_name -> pb.RequestHeader
	12, // 1: pb.ListLongConnectionReq.filter:type_name -> pb.ListLongConnectionReq.Filter
	16, // 2: pb.ListLongConnectionResp.header:type_name -> pb.ResponseHeader
	17, // 3: pb.ListLongConnectionResp.longConnections:type_name -> pb.LongConnection
	15, // 4: pb.GatewayKickLongConnectionReq.header:type_name -> pb.RequestHeader
	13, // 5: pb.GatewayKickLongConnectionReq.filter:type_name -> pb.GatewayKickLongConnectionReq.Filter
	16, // 6: pb.GatewayKickLongConnectionResp.header:type_name -> pb.ResponseHeader
	17, // 7: pb.GatewayKickLongConnectionResp.successLongConnections:type_name -> pb.LongConnection
	15, // 8: pb.GatewayKeepAliveReq.header:type_name -> pb.RequestHeader
	16, // 9: pb.GatewayKeepAliveResp.header:type_name -> pb.ResponseHeader
	15, // 10: pb.VerifyConnectionReq.header:type_name -> pb.RequestHeader
	16, // 11: pb.VerifyConnectionResp.header:type_name -> pb.ResponseHeader
	15, // 12: pb.AuthConnectionReq.header:type_name -> pb.RequestHeader
	16, // 13: pb.AuthConnectionResp.header:type_name -> pb.ResponseHeader
	15, // 14: pb.GatewayWriteDataReq.header:type_name -> pb.RequestHeader
	14, // 15: pb.GatewayWriteDataReq.filter:type_name -> pb.GatewayWriteDataReq.Filter
	18, // 16: pb.GatewayWriteDataReq.content:type_name -> pb.GatewayWriteDataContent
	16, // 17: pb.GatewayWriteDataResp.header:type_name -> pb.ResponseHeader
	17, // 18: pb.GatewayWriteDataResp.successLongConnections:type_name -> pb.LongConnection
	0,  // 19: pb.connectionService.ListLongConnection:input_type -> pb.ListLongConnectionReq
	2,  // 20: pb.connectionService.GatewayKickLongConnection:input_type -> pb.GatewayKickLongConnectionReq
	4,  // 21: pb.interfaceService.GatewayKeepAlive:input_type -> pb.GatewayKeepAliveReq
	6,  // 22: pb.interfaceService.VerifyConnection:input_type -> pb.VerifyConnectionReq
	8,  // 23: pb.interfaceService.AuthConnection:input_type -> pb.AuthConnectionReq
	10, // 24: pb.internalService.GatewayWriteData:input_type -> pb.GatewayWriteDataReq
	1,  // 25: pb.connectionService.ListLongConnection:output_type -> pb.ListLongConnectionResp
	3,  // 26: pb.connectionService.GatewayKickLongConnection:output_type -> pb.GatewayKickLongConnectionResp
	5,  // 27: pb.interfaceService.GatewayKeepAlive:output_type -> pb.GatewayKeepAliveResp
	7,  // 28: pb.interfaceService.VerifyConnection:output_type -> pb.VerifyConnectionResp
	9,  // 29: pb.interfaceService.AuthConnection:output_type -> pb.AuthConnectionResp
	11, // 30: pb.internalService.GatewayWriteData:output_type -> pb.GatewayWriteDataResp
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_gateway_peer_proto_init() }
func file_gateway_peer_proto_init() {
	if File_gateway_peer_proto != nil {
		return
	}
	file_types_peer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gateway_peer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLongConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLongConnectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayKickLongConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayKickLongConnectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayKeepAliveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayKeepAliveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyConnectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConnectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayWriteDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayWriteDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLongConnectionReq_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayKickLongConnectionReq_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_peer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayWriteDataReq_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gateway_peer_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_gateway_peer_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_gateway_peer_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_gateway_peer_proto_goTypes,
		DependencyIndexes: file_gateway_peer_proto_depIdxs,
		MessageInfos:      file_gateway_peer_proto_msgTypes,
	}.Build()
	File_gateway_peer_proto = out.File
	file_gateway_peer_proto_rawDesc = nil
	file_gateway_peer_proto_goTypes = nil
	file_gateway_peer_proto_depIdxs = nil
}
