// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: message.peer.proto

package peerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageContentText_Item_Type int32

const (
	//文本
	MessageContentText_Item_TEXT MessageContentText_Item_Type = 0
	//图片
	MessageContentText_Item_IMAGE MessageContentText_Item_Type = 1
	//@
	MessageContentText_Item_AT MessageContentText_Item_Type = 2
)

// Enum value maps for MessageContentText_Item_Type.
var (
	MessageContentText_Item_Type_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "AT",
	}
	MessageContentText_Item_Type_value = map[string]int32{
		"TEXT":  0,
		"IMAGE": 1,
		"AT":    2,
	}
)

func (x MessageContentText_Item_Type) Enum() *MessageContentText_Item_Type {
	p := new(MessageContentText_Item_Type)
	*p = x
	return p
}

func (x MessageContentText_Item_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageContentText_Item_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_message_peer_proto_enumTypes[0].Descriptor()
}

func (MessageContentText_Item_Type) Type() protoreflect.EnumType {
	return &file_message_peer_proto_enumTypes[0]
}

func (x MessageContentText_Item_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageContentText_Item_Type.Descriptor instead.
func (MessageContentText_Item_Type) EnumDescriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{0, 0, 0}
}

// **************************************************** 定义消息体：消息 ***************************************************** //
//MessageContentText 图文消息
type MessageContentText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//items 图文消息
	Items []*MessageContentText_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *MessageContentText) Reset() {
	*x = MessageContentText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContentText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContentText) ProtoMessage() {}

func (x *MessageContentText) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContentText.ProtoReflect.Descriptor instead.
func (*MessageContentText) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContentText) GetItems() []*MessageContentText_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// **************************************************** 定义消息体：通知 ***************************************************** //
//NoticeContentNewFriendRequest 通知内容-新的好友请求
type NoticeContentNewFriendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeContentNewFriendRequest) Reset() {
	*x = NoticeContentNewFriendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeContentNewFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeContentNewFriendRequest) ProtoMessage() {}

func (x *NoticeContentNewFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeContentNewFriendRequest.ProtoReflect.Descriptor instead.
func (*NoticeContentNewFriendRequest) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{1}
}

//NoticeContentJoinNewGroup 通知内容-加入新群
type NoticeContentJoinNewGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *NoticeContentJoinNewGroup) Reset() {
	*x = NoticeContentJoinNewGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeContentJoinNewGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeContentJoinNewGroup) ProtoMessage() {}

func (x *NoticeContentJoinNewGroup) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeContentJoinNewGroup.ProtoReflect.Descriptor instead.
func (*NoticeContentJoinNewGroup) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{2}
}

func (x *NoticeContentJoinNewGroup) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

//NoticeContentOnlineStatus 通知内容-用户在线状态
type NoticeContentOnlineStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`  // 用户id
	Online bool   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"` // 是在线还是离线
}

func (x *NoticeContentOnlineStatus) Reset() {
	*x = NoticeContentOnlineStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeContentOnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeContentOnlineStatus) ProtoMessage() {}

func (x *NoticeContentOnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeContentOnlineStatus.ProtoReflect.Descriptor instead.
func (*NoticeContentOnlineStatus) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{3}
}

func (x *NoticeContentOnlineStatus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoticeContentOnlineStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// **************************************************** 外部 ***************************************************** //
// ************************************************** 外部: 消息 *************************************************** //
//MessageSendReq 发送消息请求
type MessageSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//消息
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	//禁止走队列
	DisableQueue bool `protobuf:"varint,3,opt,name=disableQueue,proto3" json:"disableQueue,omitempty"`
}

func (x *MessageSendReq) Reset() {
	*x = MessageSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendReq) ProtoMessage() {}

func (x *MessageSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendReq.ProtoReflect.Descriptor instead.
func (*MessageSendReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{4}
}

func (x *MessageSendReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MessageSendReq) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageSendReq) GetDisableQueue() bool {
	if x != nil {
		return x.DisableQueue
	}
	return false
}

//MessageSendResp 发送消息响应
type MessageSendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MessageSendResp) Reset() {
	*x = MessageSendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendResp) ProtoMessage() {}

func (x *MessageSendResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendResp.ProtoReflect.Descriptor instead.
func (*MessageSendResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSendResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MessageSendResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageSendResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//MessageInsertReq 插入消息请求
type MessageInsertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//消息
	Messages []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MessageInsertReq) Reset() {
	*x = MessageInsertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInsertReq) ProtoMessage() {}

func (x *MessageInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInsertReq.ProtoReflect.Descriptor instead.
func (*MessageInsertReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{6}
}

func (x *MessageInsertReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MessageInsertReq) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

//MessageInsertResp 插入消息响应
type MessageInsertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *MessageInsertResp) Reset() {
	*x = MessageInsertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInsertResp) ProtoMessage() {}

func (x *MessageInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInsertResp.ProtoReflect.Descriptor instead.
func (*MessageInsertResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{7}
}

func (x *MessageInsertResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//MessagePushReq 推送消息请求
type MessagePushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//消息
	Message []*Message `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *MessagePushReq) Reset() {
	*x = MessagePushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePushReq) ProtoMessage() {}

func (x *MessagePushReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePushReq.ProtoReflect.Descriptor instead.
func (*MessagePushReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{8}
}

func (x *MessagePushReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MessagePushReq) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

//MessagePushResp 推送消息响应
type MessagePushResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *MessagePushResp) Reset() {
	*x = MessagePushResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePushResp) ProtoMessage() {}

func (x *MessagePushResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePushResp.ProtoReflect.Descriptor instead.
func (*MessagePushResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{9}
}

func (x *MessagePushResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//GetConvMessageSeqReq 获取会话消息序列号请求
type GetConvMessageSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//会话id
	ConvId string `protobuf:"bytes,2,opt,name=convId,proto3" json:"convId,omitempty"`
	//会话类型
	ConvType ConversationType `protobuf:"varint,3,opt,name=convType,proto3,enum=pb.ConversationType" json:"convType,omitempty"`
}

func (x *GetConvMessageSeqReq) Reset() {
	*x = GetConvMessageSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConvMessageSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvMessageSeqReq) ProtoMessage() {}

func (x *GetConvMessageSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvMessageSeqReq.ProtoReflect.Descriptor instead.
func (*GetConvMessageSeqReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{10}
}

func (x *GetConvMessageSeqReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetConvMessageSeqReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *GetConvMessageSeqReq) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_Single
}

//GetConvMessageSeqResp 获取会话消息序列号响应
type GetConvMessageSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//会话id
	ConvId   string           `protobuf:"bytes,2,opt,name=convId,proto3" json:"convId,omitempty"`
	ConvType ConversationType `protobuf:"varint,3,opt,name=convType,proto3,enum=pb.ConversationType" json:"convType,omitempty"`
	MinSeq   uint32           `protobuf:"varint,4,opt,name=minSeq,proto3" json:"minSeq,omitempty"`
	MaxSeq   uint32           `protobuf:"varint,5,opt,name=maxSeq,proto3" json:"maxSeq,omitempty"`
}

func (x *GetConvMessageSeqResp) Reset() {
	*x = GetConvMessageSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConvMessageSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvMessageSeqResp) ProtoMessage() {}

func (x *GetConvMessageSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvMessageSeqResp.ProtoReflect.Descriptor instead.
func (*GetConvMessageSeqResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{11}
}

func (x *GetConvMessageSeqResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetConvMessageSeqResp) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *GetConvMessageSeqResp) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_Single
}

func (x *GetConvMessageSeqResp) GetMinSeq() uint32 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

func (x *GetConvMessageSeqResp) GetMaxSeq() uint32 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

//SyncMessageReq 同步消息请求
type SyncMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//会话id
	ConvId string `protobuf:"bytes,2,opt,name=convId,proto3" json:"convId,omitempty"`
	//会话类型
	ConvType ConversationType `protobuf:"varint,3,opt,name=convType,proto3,enum=pb.ConversationType" json:"convType,omitempty"`
	//seqList
	SeqList []uint32 `protobuf:"varint,4,rep,packed,name=seqList,proto3" json:"seqList,omitempty"`
}

func (x *SyncMessageReq) Reset() {
	*x = SyncMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageReq) ProtoMessage() {}

func (x *SyncMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageReq.ProtoReflect.Descriptor instead.
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{12}
}

func (x *SyncMessageReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SyncMessageReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *SyncMessageReq) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_Single
}

func (x *SyncMessageReq) GetSeqList() []uint32 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

//SyncMessageResp 同步消息响应
type SyncMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//会话id
	ConvId   string           `protobuf:"bytes,2,opt,name=convId,proto3" json:"convId,omitempty"`
	ConvType ConversationType `protobuf:"varint,3,opt,name=convType,proto3,enum=pb.ConversationType" json:"convType,omitempty"`
	//消息
	Messages []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SyncMessageResp) Reset() {
	*x = SyncMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessageResp) ProtoMessage() {}

func (x *SyncMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessageResp.ProtoReflect.Descriptor instead.
func (*SyncMessageResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{13}
}

func (x *SyncMessageResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SyncMessageResp) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *SyncMessageResp) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_Single
}

func (x *SyncMessageResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type NoticeSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Notices []*Message     `protobuf:"bytes,2,rep,name=notices,proto3" json:"notices,omitempty"`
}

func (x *NoticeSendReq) Reset() {
	*x = NoticeSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeSendReq) ProtoMessage() {}

func (x *NoticeSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeSendReq.ProtoReflect.Descriptor instead.
func (*NoticeSendReq) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{14}
}

func (x *NoticeSendReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NoticeSendReq) GetNotices() []*Message {
	if x != nil {
		return x.Notices
	}
	return nil
}

type NoticeSendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *NoticeSendResp) Reset() {
	*x = NoticeSendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeSendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeSendResp) ProtoMessage() {}

func (x *NoticeSendResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeSendResp.ProtoReflect.Descriptor instead.
func (*NoticeSendResp) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{15}
}

func (x *NoticeSendResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type MessageContentText_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//类型
	Type MessageContentText_Item_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MessageContentText_Item_Type" json:"type,omitempty"`
	//文本
	Text  string                         `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Image *MessageContentText_Item_Image `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	At    *MessageContentText_Item_At    `protobuf:"bytes,4,opt,name=at,proto3,oneof" json:"at,omitempty"`
}

func (x *MessageContentText_Item) Reset() {
	*x = MessageContentText_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContentText_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContentText_Item) ProtoMessage() {}

func (x *MessageContentText_Item) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContentText_Item.ProtoReflect.Descriptor instead.
func (*MessageContentText_Item) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessageContentText_Item) GetType() MessageContentText_Item_Type {
	if x != nil {
		return x.Type
	}
	return MessageContentText_Item_TEXT
}

func (x *MessageContentText_Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContentText_Item) GetImage() *MessageContentText_Item_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *MessageContentText_Item) GetAt() *MessageContentText_Item_At {
	if x != nil {
		return x.At
	}
	return nil
}

//图片
type MessageContentText_Item_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//图片地址
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	//宽度
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	//高度
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *MessageContentText_Item_Image) Reset() {
	*x = MessageContentText_Item_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContentText_Item_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContentText_Item_Image) ProtoMessage() {}

func (x *MessageContentText_Item_Image) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContentText_Item_Image.ProtoReflect.Descriptor instead.
func (*MessageContentText_Item_Image) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MessageContentText_Item_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageContentText_Item_Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MessageContentText_Item_Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

//@用户信息
type MessageContentText_Item_At struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户id
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	//用户名称, 渲染时先获取用户本地信息中的备注，如果没有备注，那么就显示该名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MessageContentText_Item_At) Reset() {
	*x = MessageContentText_Item_At{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_peer_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContentText_Item_At) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContentText_Item_At) ProtoMessage() {}

func (x *MessageContentText_Item_At) ProtoReflect() protoreflect.Message {
	mi := &file_message_peer_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContentText_Item_At.ProtoReflect.Descriptor instead.
func (*MessageContentText_Item_At) Descriptor() ([]byte, []int) {
	return file_message_peer_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *MessageContentText_Item_At) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MessageContentText_Item_At) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_message_peer_proto protoreflect.FileDescriptor

var file_message_peer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x03, 0x0a, 0x12, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x1a, 0xf4, 0x02, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x34, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x65, 0x78, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x41,
	0x74, 0x48, 0x01, 0x52, 0x02, 0x61, 0x74, 0x88, 0x01, 0x01, 0x1a, 0x47, 0x0a, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x1a, 0x30, 0x0a, 0x02, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41, 0x47, 0x45,
	0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x54, 0x10, 0x02, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x61, 0x74, 0x22, 0x1f, 0x0a, 0x1d, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x19,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x4e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x19, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x22, 0x86, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0x6d, 0x0a, 0x0f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x66, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x3f, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x62, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x76,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x76,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x78, 0x53, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53,
	0x65, 0x71, 0x22, 0x9f, 0x01, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x76,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x71, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x71,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x32, 0xc0, 0x02, 0x0a, 0x0e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x71, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x71, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x44, 0x0a, 0x0d, 0x6e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0a,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_peer_proto_rawDescOnce sync.Once
	file_message_peer_proto_rawDescData = file_message_peer_proto_rawDesc
)

func file_message_peer_proto_rawDescGZIP() []byte {
	file_message_peer_proto_rawDescOnce.Do(func() {
		file_message_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_peer_proto_rawDescData)
	})
	return file_message_peer_proto_rawDescData
}

var file_message_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_message_peer_proto_goTypes = []interface{}{
	(MessageContentText_Item_Type)(0),     // 0: pb.MessageContentText.Item.Type
	(*MessageContentText)(nil),            // 1: pb.MessageContentText
	(*NoticeContentNewFriendRequest)(nil), // 2: pb.NoticeContentNewFriendRequest
	(*NoticeContentJoinNewGroup)(nil),     // 3: pb.NoticeContentJoinNewGroup
	(*NoticeContentOnlineStatus)(nil),     // 4: pb.NoticeContentOnlineStatus
	(*MessageSendReq)(nil),                // 5: pb.MessageSendReq
	(*MessageSendResp)(nil),               // 6: pb.MessageSendResp
	(*MessageInsertReq)(nil),              // 7: pb.MessageInsertReq
	(*MessageInsertResp)(nil),             // 8: pb.MessageInsertResp
	(*MessagePushReq)(nil),                // 9: pb.MessagePushReq
	(*MessagePushResp)(nil),               // 10: pb.MessagePushResp
	(*GetConvMessageSeqReq)(nil),          // 11: pb.GetConvMessageSeqReq
	(*GetConvMessageSeqResp)(nil),         // 12: pb.GetConvMessageSeqResp
	(*SyncMessageReq)(nil),                // 13: pb.SyncMessageReq
	(*SyncMessageResp)(nil),               // 14: pb.SyncMessageResp
	(*NoticeSendReq)(nil),                 // 15: pb.NoticeSendReq
	(*NoticeSendResp)(nil),                // 16: pb.NoticeSendResp
	(*MessageContentText_Item)(nil),       // 17: pb.MessageContentText.Item
	(*MessageContentText_Item_Image)(nil), // 18: pb.MessageContentText.Item.Image
	(*MessageContentText_Item_At)(nil),    // 19: pb.MessageContentText.Item.At
	(*RequestHeader)(nil),                 // 20: pb.RequestHeader
	(*Message)(nil),                       // 21: pb.Message
	(*ResponseHeader)(nil),                // 22: pb.ResponseHeader
	(ConversationType)(0),                 // 23: pb.ConversationType
}
var file_message_peer_proto_depIdxs = []int32{
	17, // 0: pb.MessageContentText.items:type_name -> pb.MessageContentText.Item
	20, // 1: pb.MessageSendReq.header:type_name -> pb.RequestHeader
	21, // 2: pb.MessageSendReq.message:type_name -> pb.Message
	22, // 3: pb.MessageSendResp.header:type_name -> pb.ResponseHeader
	20, // 4: pb.MessageInsertReq.header:type_name -> pb.RequestHeader
	21, // 5: pb.MessageInsertReq.messages:type_name -> pb.Message
	22, // 6: pb.MessageInsertResp.header:type_name -> pb.ResponseHeader
	20, // 7: pb.MessagePushReq.header:type_name -> pb.RequestHeader
	21, // 8: pb.MessagePushReq.message:type_name -> pb.Message
	22, // 9: pb.MessagePushResp.header:type_name -> pb.ResponseHeader
	20, // 10: pb.GetConvMessageSeqReq.header:type_name -> pb.RequestHeader
	23, // 11: pb.GetConvMessageSeqReq.convType:type_name -> pb.ConversationType
	22, // 12: pb.GetConvMessageSeqResp.header:type_name -> pb.ResponseHeader
	23, // 13: pb.GetConvMessageSeqResp.convType:type_name -> pb.ConversationType
	20, // 14: pb.SyncMessageReq.header:type_name -> pb.RequestHeader
	23, // 15: pb.SyncMessageReq.convType:type_name -> pb.ConversationType
	22, // 16: pb.SyncMessageResp.header:type_name -> pb.ResponseHeader
	23, // 17: pb.SyncMessageResp.convType:type_name -> pb.ConversationType
	21, // 18: pb.SyncMessageResp.messages:type_name -> pb.Message
	20, // 19: pb.NoticeSendReq.header:type_name -> pb.RequestHeader
	21, // 20: pb.NoticeSendReq.notices:type_name -> pb.Message
	22, // 21: pb.NoticeSendResp.header:type_name -> pb.ResponseHeader
	0,  // 22: pb.MessageContentText.Item.type:type_name -> pb.MessageContentText.Item.Type
	18, // 23: pb.MessageContentText.Item.image:type_name -> pb.MessageContentText.Item.Image
	19, // 24: pb.MessageContentText.Item.at:type_name -> pb.MessageContentText.Item.At
	7,  // 25: pb.messageService.MessageInsert:input_type -> pb.MessageInsertReq
	5,  // 26: pb.messageService.MessageSend:input_type -> pb.MessageSendReq
	9,  // 27: pb.messageService.MessagePush:input_type -> pb.MessagePushReq
	11, // 28: pb.messageService.GetConvMessageSeq:input_type -> pb.GetConvMessageSeqReq
	13, // 29: pb.messageService.SyncMessage:input_type -> pb.SyncMessageReq
	15, // 30: pb.noticeService.NoticeSend:input_type -> pb.NoticeSendReq
	8,  // 31: pb.messageService.MessageInsert:output_type -> pb.MessageInsertResp
	6,  // 32: pb.messageService.MessageSend:output_type -> pb.MessageSendResp
	10, // 33: pb.messageService.MessagePush:output_type -> pb.MessagePushResp
	12, // 34: pb.messageService.GetConvMessageSeq:output_type -> pb.GetConvMessageSeqResp
	14, // 35: pb.messageService.SyncMessage:output_type -> pb.SyncMessageResp
	16, // 36: pb.noticeService.NoticeSend:output_type -> pb.NoticeSendResp
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_message_peer_proto_init() }
func file_message_peer_proto_init() {
	if File_message_peer_proto != nil {
		return
	}
	file_types_peer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_peer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContentText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeContentNewFriendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeContentJoinNewGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeContentOnlineStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInsertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInsertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePushResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConvMessageSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConvMessageSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeSendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContentText_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContentText_Item_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_peer_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContentText_Item_At); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_peer_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_peer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_message_peer_proto_goTypes,
		DependencyIndexes: file_message_peer_proto_depIdxs,
		EnumInfos:         file_message_peer_proto_enumTypes,
		MessageInfos:      file_message_peer_proto_msgTypes,
	}.Build()
	File_message_peer_proto = out.File
	file_message_peer_proto_rawDesc = nil
	file_message_peer_proto_goTypes = nil
	file_message_peer_proto_depIdxs = nil
}
