// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: third.peer.proto

package peerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **************************************************** 定义枚举 ***************************************************** //
type SmsSceneType int32

const (
	SmsSceneType_SmsUserToken SmsSceneType = 0 //用户获取token
	SmsSceneType_SmsRegister  SmsSceneType = 1 //注册
)

// Enum value maps for SmsSceneType.
var (
	SmsSceneType_name = map[int32]string{
		0: "SmsUserToken",
		1: "SmsRegister",
	}
	SmsSceneType_value = map[string]int32{
		"SmsUserToken": 0,
		"SmsRegister":  1,
	}
)

func (x SmsSceneType) Enum() *SmsSceneType {
	p := new(SmsSceneType)
	*p = x
	return p
}

func (x SmsSceneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsSceneType) Descriptor() protoreflect.EnumDescriptor {
	return file_third_peer_proto_enumTypes[0].Descriptor()
}

func (SmsSceneType) Type() protoreflect.EnumType {
	return &file_third_peer_proto_enumTypes[0]
}

func (x SmsSceneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsSceneType.Descriptor instead.
func (SmsSceneType) EnumDescriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{0}
}

type EmailSceneType int32

const (
	EmailSceneType_EmailUserToken EmailSceneType = 0 //用户获取token
	EmailSceneType_EmailRegister  EmailSceneType = 1 //注册
)

// Enum value maps for EmailSceneType.
var (
	EmailSceneType_name = map[int32]string{
		0: "EmailUserToken",
		1: "EmailRegister",
	}
	EmailSceneType_value = map[string]int32{
		"EmailUserToken": 0,
		"EmailRegister":  1,
	}
)

func (x EmailSceneType) Enum() *EmailSceneType {
	p := new(EmailSceneType)
	*p = x
	return p
}

func (x EmailSceneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailSceneType) Descriptor() protoreflect.EnumDescriptor {
	return file_third_peer_proto_enumTypes[1].Descriptor()
}

func (EmailSceneType) Type() protoreflect.EnumType {
	return &file_third_peer_proto_enumTypes[1]
}

func (x EmailSceneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailSceneType.Descriptor instead.
func (EmailSceneType) EnumDescriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{1}
}

//SmsCodeSendReq 发送短信请求
type SmsCodeSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//手机号
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	//手机国家区号
	PhoneCode string `protobuf:"bytes,3,opt,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	//短信场景
	Scene string `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	//过期时间
	ExpireTime *uint32 `protobuf:"varint,5,opt,name=expireTime,proto3,oneof" json:"expireTime,omitempty"`
}

func (x *SmsCodeSendReq) Reset() {
	*x = SmsCodeSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeSendReq) ProtoMessage() {}

func (x *SmsCodeSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeSendReq.ProtoReflect.Descriptor instead.
func (*SmsCodeSendReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{0}
}

func (x *SmsCodeSendReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SmsCodeSendReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SmsCodeSendReq) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *SmsCodeSendReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *SmsCodeSendReq) GetExpireTime() uint32 {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return 0
}

//SmsCodeSendResp 发送短信响应
type SmsCodeSendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *SmsCodeSendResp) Reset() {
	*x = SmsCodeSendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeSendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeSendResp) ProtoMessage() {}

func (x *SmsCodeSendResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeSendResp.ProtoReflect.Descriptor instead.
func (*SmsCodeSendResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{1}
}

func (x *SmsCodeSendResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//SmsCodeVerifyReq 验证短信请求
type SmsCodeVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//手机号
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	//手机国家区号
	PhoneCode string `protobuf:"bytes,3,opt,name=phoneCode,proto3" json:"phoneCode,omitempty"`
	//短信场景
	Scene string `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	//验证码
	SmsCode string `protobuf:"bytes,5,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	//是否立刻删除 删除后再次验证会失败
	Delete bool `protobuf:"varint,6,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *SmsCodeVerifyReq) Reset() {
	*x = SmsCodeVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeVerifyReq) ProtoMessage() {}

func (x *SmsCodeVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeVerifyReq.ProtoReflect.Descriptor instead.
func (*SmsCodeVerifyReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{2}
}

func (x *SmsCodeVerifyReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SmsCodeVerifyReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SmsCodeVerifyReq) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *SmsCodeVerifyReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *SmsCodeVerifyReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *SmsCodeVerifyReq) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

//SmsCodeVerifyResp 验证短信响应
type SmsCodeVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SmsCodeVerifyResp) Reset() {
	*x = SmsCodeVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeVerifyResp) ProtoMessage() {}

func (x *SmsCodeVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeVerifyResp.ProtoReflect.Descriptor instead.
func (*SmsCodeVerifyResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{3}
}

func (x *SmsCodeVerifyResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SmsCodeVerifyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

//EmailCodeSendReq 发送邮件请求
type EmailCodeSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//邮件地址
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	//场景
	Scene string `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	//过期时间
	ExpireTime *uint32 `protobuf:"varint,4,opt,name=expireTime,proto3,oneof" json:"expireTime,omitempty"`
}

func (x *EmailCodeSendReq) Reset() {
	*x = EmailCodeSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCodeSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCodeSendReq) ProtoMessage() {}

func (x *EmailCodeSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCodeSendReq.ProtoReflect.Descriptor instead.
func (*EmailCodeSendReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{4}
}

func (x *EmailCodeSendReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EmailCodeSendReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailCodeSendReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *EmailCodeSendReq) GetExpireTime() uint32 {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return 0
}

//EmailCodeSendResp 发送邮件响应
type EmailCodeSendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *EmailCodeSendResp) Reset() {
	*x = EmailCodeSendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCodeSendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCodeSendResp) ProtoMessage() {}

func (x *EmailCodeSendResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCodeSendResp.ProtoReflect.Descriptor instead.
func (*EmailCodeSendResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{5}
}

func (x *EmailCodeSendResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//EmailCodeVerifyReq 验证邮件请求
type EmailCodeVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//邮件地址
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	//场景
	Scene string `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	//验证码
	EmailCode string `protobuf:"bytes,4,opt,name=emailCode,proto3" json:"emailCode,omitempty"`
	//是否立刻删除 删除后再次验证会失败
	Delete bool `protobuf:"varint,5,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *EmailCodeVerifyReq) Reset() {
	*x = EmailCodeVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCodeVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCodeVerifyReq) ProtoMessage() {}

func (x *EmailCodeVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCodeVerifyReq.ProtoReflect.Descriptor instead.
func (*EmailCodeVerifyReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{6}
}

func (x *EmailCodeVerifyReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EmailCodeVerifyReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailCodeVerifyReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *EmailCodeVerifyReq) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

func (x *EmailCodeVerifyReq) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

//EmailCodeVerifyResp 验证邮件响应
type EmailCodeVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *EmailCodeVerifyResp) Reset() {
	*x = EmailCodeVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCodeVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCodeVerifyResp) ProtoMessage() {}

func (x *EmailCodeVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCodeVerifyResp.ProtoReflect.Descriptor instead.
func (*EmailCodeVerifyResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{7}
}

func (x *EmailCodeVerifyResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EmailCodeVerifyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

//GetCaptchaReq 获取图形验证码请求
type GetCaptchaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//过期时间
	ExpireTime *uint32 `protobuf:"varint,2,opt,name=expireTime,proto3,oneof" json:"expireTime,omitempty"`
	//字符是否包含英文
	IncludeEnglish bool `protobuf:"varint,3,opt,name=includeEnglish,proto3" json:"includeEnglish,omitempty"`
	//字符是否包含数字
	IncludeNumber bool `protobuf:"varint,4,opt,name=includeNumber,proto3" json:"includeNumber,omitempty"`
	//宽度
	Width int32 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	//高度
	Height int32 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	//字符数量
	CharCount int32 `protobuf:"varint,7,opt,name=charCount,proto3" json:"charCount,omitempty"`
}

func (x *GetCaptchaReq) Reset() {
	*x = GetCaptchaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReq) ProtoMessage() {}

func (x *GetCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReq.ProtoReflect.Descriptor instead.
func (*GetCaptchaReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{8}
}

func (x *GetCaptchaReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCaptchaReq) GetExpireTime() uint32 {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return 0
}

func (x *GetCaptchaReq) GetIncludeEnglish() bool {
	if x != nil {
		return x.IncludeEnglish
	}
	return false
}

func (x *GetCaptchaReq) GetIncludeNumber() bool {
	if x != nil {
		return x.IncludeNumber
	}
	return false
}

func (x *GetCaptchaReq) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetCaptchaReq) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetCaptchaReq) GetCharCount() int32 {
	if x != nil {
		return x.CharCount
	}
	return 0
}

//GetCaptchaResp 获取图形验证码响应
type GetCaptchaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//验证码id
	CaptchaId string `protobuf:"bytes,2,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	//图形验证码
	CaptchaCode string `protobuf:"bytes,3,opt,name=captchaCode,proto3" json:"captchaCode,omitempty"`
}

func (x *GetCaptchaResp) Reset() {
	*x = GetCaptchaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResp) ProtoMessage() {}

func (x *GetCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResp.ProtoReflect.Descriptor instead.
func (*GetCaptchaResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{9}
}

func (x *GetCaptchaResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCaptchaResp) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GetCaptchaResp) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

//CaptchaVerifyReq 验证图形验证码请求
type CaptchaVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//验证码id
	CaptchaId string `protobuf:"bytes,2,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	//验证码
	CaptchaCode string `protobuf:"bytes,3,opt,name=captchaCode,proto3" json:"captchaCode,omitempty"`
	//是否立刻删除 删除后再次验证会失败
	Delete bool `protobuf:"varint,4,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *CaptchaVerifyReq) Reset() {
	*x = CaptchaVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaVerifyReq) ProtoMessage() {}

func (x *CaptchaVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaVerifyReq.ProtoReflect.Descriptor instead.
func (*CaptchaVerifyReq) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{10}
}

func (x *CaptchaVerifyReq) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CaptchaVerifyReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaVerifyReq) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

func (x *CaptchaVerifyReq) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

//CaptchaVerifyResp 验证图形验证码响应
type CaptchaVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Success bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CaptchaVerifyResp) Reset() {
	*x = CaptchaVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_peer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptchaVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaVerifyResp) ProtoMessage() {}

func (x *CaptchaVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_peer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaVerifyResp.ProtoReflect.Descriptor instead.
func (*CaptchaVerifyResp) Descriptor() ([]byte, []int) {
	return file_third_peer_proto_rawDescGZIP(), []int{11}
}

func (x *CaptchaVerifyResp) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CaptchaVerifyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_third_peer_proto protoreflect.FileDescriptor

var file_third_peer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x0e, 0x53, 0x6d, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x12, 0x23, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x22, 0xb9, 0x01, 0x0a, 0x10, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22,
	0x59, 0x0a, 0x11, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x10, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0xa1, 0x01, 0x0a, 0x12,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22,
	0x5b, 0x0a, 0x13, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x88, 0x02, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x12, 0x29,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x26,
	0x0a, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x45,
	0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x59, 0x0a,
	0x11, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x31, 0x0a, 0x0c, 0x53, 0x6d, 0x73, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x6d, 0x73, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x6d,
	0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x01, 0x2a, 0x37, 0x0a, 0x0e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x0e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x10, 0x01, 0x32, 0x86, 0x01, 0x0a, 0x0a, 0x73, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6d, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0d, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x94, 0x01,
	0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x0f, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x32, 0x87, 0x01, 0x0a, 0x0e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0d, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_third_peer_proto_rawDescOnce sync.Once
	file_third_peer_proto_rawDescData = file_third_peer_proto_rawDesc
)

func file_third_peer_proto_rawDescGZIP() []byte {
	file_third_peer_proto_rawDescOnce.Do(func() {
		file_third_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_third_peer_proto_rawDescData)
	})
	return file_third_peer_proto_rawDescData
}

var file_third_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_third_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_third_peer_proto_goTypes = []interface{}{
	(SmsSceneType)(0),           // 0: pb.SmsSceneType
	(EmailSceneType)(0),         // 1: pb.EmailSceneType
	(*SmsCodeSendReq)(nil),      // 2: pb.SmsCodeSendReq
	(*SmsCodeSendResp)(nil),     // 3: pb.SmsCodeSendResp
	(*SmsCodeVerifyReq)(nil),    // 4: pb.SmsCodeVerifyReq
	(*SmsCodeVerifyResp)(nil),   // 5: pb.SmsCodeVerifyResp
	(*EmailCodeSendReq)(nil),    // 6: pb.EmailCodeSendReq
	(*EmailCodeSendResp)(nil),   // 7: pb.EmailCodeSendResp
	(*EmailCodeVerifyReq)(nil),  // 8: pb.EmailCodeVerifyReq
	(*EmailCodeVerifyResp)(nil), // 9: pb.EmailCodeVerifyResp
	(*GetCaptchaReq)(nil),       // 10: pb.GetCaptchaReq
	(*GetCaptchaResp)(nil),      // 11: pb.GetCaptchaResp
	(*CaptchaVerifyReq)(nil),    // 12: pb.CaptchaVerifyReq
	(*CaptchaVerifyResp)(nil),   // 13: pb.CaptchaVerifyResp
	(*RequestHeader)(nil),       // 14: pb.RequestHeader
	(*ResponseHeader)(nil),      // 15: pb.ResponseHeader
}
var file_third_peer_proto_depIdxs = []int32{
	14, // 0: pb.SmsCodeSendReq.header:type_name -> pb.RequestHeader
	15, // 1: pb.SmsCodeSendResp.header:type_name -> pb.ResponseHeader
	14, // 2: pb.SmsCodeVerifyReq.header:type_name -> pb.RequestHeader
	15, // 3: pb.SmsCodeVerifyResp.header:type_name -> pb.ResponseHeader
	14, // 4: pb.EmailCodeSendReq.header:type_name -> pb.RequestHeader
	15, // 5: pb.EmailCodeSendResp.header:type_name -> pb.ResponseHeader
	14, // 6: pb.EmailCodeVerifyReq.header:type_name -> pb.RequestHeader
	15, // 7: pb.EmailCodeVerifyResp.header:type_name -> pb.ResponseHeader
	14, // 8: pb.GetCaptchaReq.header:type_name -> pb.RequestHeader
	15, // 9: pb.GetCaptchaResp.header:type_name -> pb.ResponseHeader
	14, // 10: pb.CaptchaVerifyReq.header:type_name -> pb.RequestHeader
	15, // 11: pb.CaptchaVerifyResp.header:type_name -> pb.ResponseHeader
	2,  // 12: pb.smsService.SmsCodeSend:input_type -> pb.SmsCodeSendReq
	4,  // 13: pb.smsService.SmsCodeVerify:input_type -> pb.SmsCodeVerifyReq
	6,  // 14: pb.emailService.EmailCodeSend:input_type -> pb.EmailCodeSendReq
	8,  // 15: pb.emailService.EmailCodeVerify:input_type -> pb.EmailCodeVerifyReq
	10, // 16: pb.captchaService.GetCaptcha:input_type -> pb.GetCaptchaReq
	12, // 17: pb.captchaService.CaptchaVerify:input_type -> pb.CaptchaVerifyReq
	3,  // 18: pb.smsService.SmsCodeSend:output_type -> pb.SmsCodeSendResp
	5,  // 19: pb.smsService.SmsCodeVerify:output_type -> pb.SmsCodeVerifyResp
	7,  // 20: pb.emailService.EmailCodeSend:output_type -> pb.EmailCodeSendResp
	9,  // 21: pb.emailService.EmailCodeVerify:output_type -> pb.EmailCodeVerifyResp
	11, // 22: pb.captchaService.GetCaptcha:output_type -> pb.GetCaptchaResp
	13, // 23: pb.captchaService.CaptchaVerify:output_type -> pb.CaptchaVerifyResp
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_third_peer_proto_init() }
func file_third_peer_proto_init() {
	if File_third_peer_proto != nil {
		return
	}
	file_types_peer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_third_peer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeSendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCodeSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCodeSendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCodeVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCodeVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_peer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptchaVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_third_peer_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_third_peer_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_third_peer_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_third_peer_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_third_peer_proto_goTypes,
		DependencyIndexes: file_third_peer_proto_depIdxs,
		EnumInfos:         file_third_peer_proto_enumTypes,
		MessageInfos:      file_third_peer_proto_msgTypes,
	}.Build()
	File_third_peer_proto = out.File
	file_third_peer_proto_rawDesc = nil
	file_third_peer_proto_goTypes = nil
	file_third_peer_proto_depIdxs = nil
}
